version: '3'
services:
  app1:
    build: ./app1
    container_name: app1
    ports:
      - "8080:8080"
    networks:
      - appnet

  app2:
    build: ./app2
    container_name: app2
    depends_on:
      - app1
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
