version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  app:
    build: .
    container_name: go-gin-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongo:27017

networks:
  app-network:
    driver: bridge
